function [info_lines, info_viol] = build_selection_gate_info_columns( ...
    ci, template_corr_vec, emg_hf_slope_vec, min_template_corr, ...
    occdom_vec, emg_temp_vec)
% Build QC text lines for gates (template_r, EMG_hf_slope) plus occdom/EMG_temp.
template_corr_val = template_corr_vec(ci);
emg_hf_val = emg_hf_slope_vec(ci);
occdom_val = occdom_vec(ci);
emg_temp_val = emg_temp_vec(ci);
fail_template = ~(isfinite(template_corr_val) && template_corr_val >= min_template_corr);
fail_emg_hf = isfinite(emg_hf_val) && emg_hf_val > 0;
info_lines = { ...
    sprintf('template_r: %.2f (>= %.2f)', template_corr_val, min_template_corr), ...
    sprintf('EMG_hf_slope: %.2f (<= 0)', emg_hf_val), ...
    sprintf('occdom: %.2f', occdom_val), ...
    sprintf('EMG_temp: %.2f', emg_temp_val)};
% Only hard gates are flagged red; occdom/EMG_temp are diagnostic only.
info_viol = [fail_template, fail_emg_hf, false, false];
end
