function proxy = estimate_component_artifact_proxies(filter_w, dat_per_cond, stim_window, base_window, fs, scan_freqs, tapsmofrq_hz)
% Component spectrum proxies: mean power ratio, HF slope, and line-harmonic ratio.
% Thin wrapper around the batched multi-component implementation.
proxies = estimate_components_artifact_proxies( ...
    filter_w(:), dat_per_cond, stim_window, base_window, fs, scan_freqs, tapsmofrq_hz);
if isempty(proxies)
    proxy = struct( ...
        'lineharm_ratio', NaN, ...
        'stationarity_cv', NaN, ...
        'burst_ratio', NaN, ...
        'hf_slope', NaN, ...
        'mean_pr_spectrum', nan(1, numel(scan_freqs)), ...
        'n_trials_used', 0);
    return;
end
proxy = proxies(1);
end
